---
EnableDefaultLinters: true
exclude:
  - "node_modules/**/*"
  - "vendor/**/*"
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      require: standard
      inherit_gem:
        standard: config/base.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
